publish_mode: editorial_workflow
media_folder: "/public/images" # Folder where user uploaded files should go
public_folder: "/images"
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/post
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    slug: "{{slug}}" 
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: 'MMM Do, YYYY',
          time_format: false
        }
      - {
          label: "Category",
          name: "categories",
          widget: "select",
          options: ["Advice", "News", "Guide", "Other"],
        }
      - { label: "Body", name: "body", widget: "markdown" }