backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: "images"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/post
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    path: "{{slug}}/{{slug}}"
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    # media_folder: "public/images" # Save images in the post's own folder instead of the static folder
    # public_folder: "images"
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "MMM Do, YYYY",
          time_format: false,
        }
      - {
          label: "Category",
          name: "categories",
          widget: "select",
          options: ["Advice", "News", "Guide", "Other"],
        }
      - { label: "Body", name: "body", widget: "markdown" }
